public class ItemClient {
    public static void main(String[] args) {
        Book testBook = new Book(123456, 4, "Harry Potter", "JKR");
        Video testVideo = new Video(111111, 2, "Breaking Bad", 90, "Somebody", "Intense", 2010);
        CD testCD = new CD(222222, 3, "Vibe with me", 60, "That Guy", "Vibing");
        JournalPaper testPaper = new JournalPaper(333333, 1, "Why Halloween is Scary", "Sleepy Ghost", 2020);
        System.out.println("Book Info");
        testBook.print();
        System.out.println("---------");
        System.out.println("Paper Info");
        testPaper.print();
        System.out.println("---------");
        System.out.println("Video Info");
        testVideo.print();
        System.out.println("---------");
        System.out.println("CD Info");
        testCD.print();
        System.out.println("---------");
        System.out.println("Check out every item once.");
        testBook.checkOut();
        testPaper.checkOut();
        testCD.checkOut();
        testVideo.checkOut();
        System.out.println("Book Info");
        testBook.print();
        System.out.println("---------");
        System.out.println("Paper Info");
        testPaper.print();
        System.out.println("---------");
        System.out.println("Video Info");
        testVideo.print();
        System.out.println("---------");
        System.out.println("CD Info");
        testCD.print();
        System.out.println("---------");
        System.out.println("Try to take book with no more copies.");
        testPaper.checkOut();
        System.out.println("Paper Info");
        testPaper.print();
        System.out.println("---------");
        System.out.println("Add new CD.");
        testCD.addItem();
        System.out.println("CD Info");
        testCD.print();
        System.out.println("---------");
        System.out.println("Check every item back in.");
        testBook.checkIn();
        testCD.checkIn();
        testPaper.checkIn();
        testVideo.checkIn();
        System.out.println("Book Info");
        testBook.print();
        System.out.println("---------");
        System.out.println("Paper Info");
        testPaper.print();
        System.out.println("---------");
        System.out.println("Video Info");
        testVideo.print();
        System.out.println("---------");
        System.out.println("CD Info");
        testCD.print();
        System.out.println("---------");
    }
}
